// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Packets.proto

#include "src/Packets.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ServerVerdict::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : answer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        correct_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerVerdict::ServerVerdict(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServerVerdictDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerVerdictDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerVerdictDefaultTypeInternal() {}
  union {
    ServerVerdict _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerVerdictDefaultTypeInternal _ServerVerdict_default_instance_;

inline constexpr ServerQuestion::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : question_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerQuestion::ServerQuestion(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServerQuestionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerQuestionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerQuestionDefaultTypeInternal() {}
  union {
    ServerQuestion _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerQuestionDefaultTypeInternal _ServerQuestion_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR QuizFilePathsRequest::QuizFilePathsRequest(::_pbi::ConstantInitialized) {}
struct QuizFilePathsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuizFilePathsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuizFilePathsRequestDefaultTypeInternal() {}
  union {
    QuizFilePathsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuizFilePathsRequestDefaultTypeInternal _QuizFilePathsRequest_default_instance_;

inline constexpr QuizFilePaths::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : quizpaths_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR QuizFilePaths::QuizFilePaths(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct QuizFilePathsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuizFilePathsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuizFilePathsDefaultTypeInternal() {}
  union {
    QuizFilePaths _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuizFilePathsDefaultTypeInternal _QuizFilePaths_default_instance_;

inline constexpr QuizChangeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : quizpath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        repeats_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR QuizChangeRequest::QuizChangeRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct QuizChangeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuizChangeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuizChangeRequestDefaultTypeInternal() {}
  union {
    QuizChangeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuizChangeRequestDefaultTypeInternal _QuizChangeRequest_default_instance_;

inline constexpr PlayerDataMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        score_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlayerDataMsg::PlayerDataMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PlayerDataMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDataMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDataMsgDefaultTypeInternal() {}
  union {
    PlayerDataMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDataMsgDefaultTypeInternal _PlayerDataMsg_default_instance_;

inline constexpr ClientLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientLogin::ClientLogin(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClientLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientLoginDefaultTypeInternal() {}
  union {
    ClientLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientLoginDefaultTypeInternal _ClientLogin_default_instance_;

inline constexpr ClientAnswer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        answer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientAnswer::ClientAnswer(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClientAnswerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientAnswerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientAnswerDefaultTypeInternal() {}
  union {
    ClientAnswer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientAnswerDefaultTypeInternal _ClientAnswer_default_instance_;

inline constexpr MessageEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::MessageEnvelope_MessageType >(0)},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MessageEnvelope::MessageEnvelope(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessageEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageEnvelopeDefaultTypeInternal() {}
  union {
    MessageEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageEnvelopeDefaultTypeInternal _MessageEnvelope_default_instance_;
static ::_pb::Metadata file_level_metadata_src_2fPackets_2eproto[9];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_src_2fPackets_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_src_2fPackets_2eproto = nullptr;
const ::uint32_t TableStruct_src_2fPackets_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ClientLogin, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ClientLogin, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ClientAnswer, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ClientAnswer, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::ClientAnswer, _impl_.answer_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ServerQuestion, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ServerQuestion, _impl_.question_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ServerVerdict, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ServerVerdict, _impl_.answer_),
    PROTOBUF_FIELD_OFFSET(::ServerVerdict, _impl_.correct_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::QuizFilePathsRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::QuizFilePaths, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::QuizFilePaths, _impl_.quizpaths_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::QuizChangeRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::QuizChangeRequest, _impl_.quizpath_),
    PROTOBUF_FIELD_OFFSET(::QuizChangeRequest, _impl_.repeats_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PlayerDataMsg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PlayerDataMsg, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::PlayerDataMsg, _impl_.score_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MessageEnvelope, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::MessageEnvelope, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MessageEnvelope, _impl_.type_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::MessageEnvelope, _impl_.payload_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ClientLogin)},
        {9, -1, -1, sizeof(::ClientAnswer)},
        {19, -1, -1, sizeof(::ServerQuestion)},
        {28, -1, -1, sizeof(::ServerVerdict)},
        {38, -1, -1, sizeof(::QuizFilePathsRequest)},
        {46, -1, -1, sizeof(::QuizFilePaths)},
        {55, -1, -1, sizeof(::QuizChangeRequest)},
        {65, -1, -1, sizeof(::PlayerDataMsg)},
        {75, -1, -1, sizeof(::MessageEnvelope)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_ClientLogin_default_instance_._instance,
    &::_ClientAnswer_default_instance_._instance,
    &::_ServerQuestion_default_instance_._instance,
    &::_ServerVerdict_default_instance_._instance,
    &::_QuizFilePathsRequest_default_instance_._instance,
    &::_QuizFilePaths_default_instance_._instance,
    &::_QuizChangeRequest_default_instance_._instance,
    &::_PlayerDataMsg_default_instance_._instance,
    &::_MessageEnvelope_default_instance_._instance,
};
const char descriptor_table_protodef_src_2fPackets_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021src/Packets.proto\"\033\n\013ClientLogin\022\014\n\004na"
    "me\030\001 \001(\t\",\n\014ClientAnswer\022\014\n\004name\030\001 \001(\t\022\016"
    "\n\006answer\030\002 \001(\t\"\"\n\016ServerQuestion\022\020\n\010ques"
    "tion\030\001 \001(\t\"0\n\rServerVerdict\022\016\n\006answer\030\001 "
    "\001(\t\022\017\n\007correct\030\002 \001(\010\"\026\n\024QuizFilePathsReq"
    "uest\"\"\n\rQuizFilePaths\022\021\n\tquizPaths\030\001 \003(\t"
    "\"6\n\021QuizChangeRequest\022\020\n\010quizPath\030\001 \001(\t\022"
    "\017\n\007repeats\030\002 \001(\005\",\n\rPlayerDataMsg\022\014\n\004nam"
    "e\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\"\331\004\n\017MessageEnvelo"
    "pe\022*\n\004type\030\001 \001(\0162\034.MessageEnvelope.Messa"
    "geType\022#\n\013clientLogin\030\002 \001(\0132\014.ClientLogi"
    "nH\000\022%\n\014clientAnswer\030\003 \001(\0132\r.ClientAnswer"
    "H\000\022)\n\016serverQuestion\030\004 \001(\0132\017.ServerQuest"
    "ionH\000\022\'\n\rserverVerdict\030\005 \001(\0132\016.ServerVer"
    "dictH\000\022/\n\021quizChangeRequest\030\006 \001(\0132\022.Quiz"
    "ChangeRequestH\000\0225\n\024quizFilePathsRequest\030"
    "\007 \001(\0132\025.QuizFilePathsRequestH\000\022\'\n\rquizFi"
    "lePaths\030\010 \001(\0132\016.QuizFilePathsH\000\022$\n\nplaye"
    "rData\030\t \001(\0132\016.PlayerDataMsgH\000\"\267\001\n\013Messag"
    "eType\022\020\n\014CLIENT_LOGIN\020\000\022\021\n\rCLIENT_ANSWER"
    "\020\001\022\023\n\017SERVER_QUESTION\020\002\022\022\n\016SERVER_VERDIC"
    "T\020\003\022\027\n\023QUIZ_CHANGE_REQUEST\020\004\022\033\n\027QUIZ_FIL"
    "E_PATHS_REQUEST\020\005\022\023\n\017QUIZ_FILE_PATHS\020\006\022\017"
    "\n\013PLAYER_DATA\020\007B\t\n\007payloadb\006proto3"
};
static ::absl::once_flag descriptor_table_src_2fPackets_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_src_2fPackets_2eproto = {
    false,
    false,
    954,
    descriptor_table_protodef_src_2fPackets_2eproto,
    "src/Packets.proto",
    &descriptor_table_src_2fPackets_2eproto_once,
    nullptr,
    0,
    9,
    schemas,
    file_default_instances,
    TableStruct_src_2fPackets_2eproto::offsets,
    file_level_metadata_src_2fPackets_2eproto,
    file_level_enum_descriptors_src_2fPackets_2eproto,
    file_level_service_descriptors_src_2fPackets_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_src_2fPackets_2eproto_getter() {
  return &descriptor_table_src_2fPackets_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_src_2fPackets_2eproto(&descriptor_table_src_2fPackets_2eproto);
const ::google::protobuf::EnumDescriptor* MessageEnvelope_MessageType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_src_2fPackets_2eproto);
  return file_level_enum_descriptors_src_2fPackets_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MessageEnvelope_MessageType_internal_data_[] = {
    524288u, 0u, };
bool MessageEnvelope_MessageType_IsValid(int value) {
  return 0 <= value && value <= 7;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr MessageEnvelope_MessageType MessageEnvelope::CLIENT_LOGIN;
constexpr MessageEnvelope_MessageType MessageEnvelope::CLIENT_ANSWER;
constexpr MessageEnvelope_MessageType MessageEnvelope::SERVER_QUESTION;
constexpr MessageEnvelope_MessageType MessageEnvelope::SERVER_VERDICT;
constexpr MessageEnvelope_MessageType MessageEnvelope::QUIZ_CHANGE_REQUEST;
constexpr MessageEnvelope_MessageType MessageEnvelope::QUIZ_FILE_PATHS_REQUEST;
constexpr MessageEnvelope_MessageType MessageEnvelope::QUIZ_FILE_PATHS;
constexpr MessageEnvelope_MessageType MessageEnvelope::PLAYER_DATA;
constexpr MessageEnvelope_MessageType MessageEnvelope::MessageType_MIN;
constexpr MessageEnvelope_MessageType MessageEnvelope::MessageType_MAX;
constexpr int MessageEnvelope::MessageType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class ClientLogin::_Internal {
 public:
};

ClientLogin::ClientLogin(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ClientLogin)
}
inline PROTOBUF_NDEBUG_INLINE ClientLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

ClientLogin::ClientLogin(
    ::google::protobuf::Arena* arena,
    const ClientLogin& from)
    : ::google::protobuf::Message(arena) {
  ClientLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ClientLogin)
}
inline PROTOBUF_NDEBUG_INLINE ClientLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void ClientLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClientLogin::~ClientLogin() {
  // @@protoc_insertion_point(destructor:ClientLogin)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClientLogin::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClientLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:ClientLogin)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClientLogin::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 24, 2> ClientLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClientLogin_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClientLogin, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ClientLogin, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\4\0\0\0\0\0\0"
    "ClientLogin"
    "name"
  }},
};

::uint8_t* ClientLogin::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClientLogin)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ClientLogin.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClientLogin)
  return target;
}

::size_t ClientLogin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClientLogin)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClientLogin::_class_data_ = {
    ClientLogin::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClientLogin::GetClassData() const {
  return &_class_data_;
}

void ClientLogin::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClientLogin*>(&to_msg);
  auto& from = static_cast<const ClientLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClientLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientLogin::CopyFrom(const ClientLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClientLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClientLogin::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClientLogin::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClientLogin::InternalSwap(ClientLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata ClientLogin::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[0]);
}
// ===================================================================

class ClientAnswer::_Internal {
 public:
};

ClientAnswer::ClientAnswer(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ClientAnswer)
}
inline PROTOBUF_NDEBUG_INLINE ClientAnswer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        answer_(arena, from.answer_),
        _cached_size_{0} {}

ClientAnswer::ClientAnswer(
    ::google::protobuf::Arena* arena,
    const ClientAnswer& from)
    : ::google::protobuf::Message(arena) {
  ClientAnswer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ClientAnswer)
}
inline PROTOBUF_NDEBUG_INLINE ClientAnswer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        answer_(arena),
        _cached_size_{0} {}

inline void ClientAnswer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClientAnswer::~ClientAnswer() {
  // @@protoc_insertion_point(destructor:ClientAnswer)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClientAnswer::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.answer_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClientAnswer::Clear() {
// @@protoc_insertion_point(message_clear_start:ClientAnswer)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.answer_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClientAnswer::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2> ClientAnswer::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClientAnswer_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string answer = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ClientAnswer, _impl_.answer_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClientAnswer, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ClientAnswer, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string answer = 2;
    {PROTOBUF_FIELD_OFFSET(ClientAnswer, _impl_.answer_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\4\6\0\0\0\0\0"
    "ClientAnswer"
    "name"
    "answer"
  }},
};

::uint8_t* ClientAnswer::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClientAnswer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ClientAnswer.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string answer = 2;
  if (!this->_internal_answer().empty()) {
    const std::string& _s = this->_internal_answer();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ClientAnswer.answer");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClientAnswer)
  return target;
}

::size_t ClientAnswer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClientAnswer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string answer = 2;
  if (!this->_internal_answer().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_answer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClientAnswer::_class_data_ = {
    ClientAnswer::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClientAnswer::GetClassData() const {
  return &_class_data_;
}

void ClientAnswer::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClientAnswer*>(&to_msg);
  auto& from = static_cast<const ClientAnswer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClientAnswer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_answer().empty()) {
    _this->_internal_set_answer(from._internal_answer());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientAnswer::CopyFrom(const ClientAnswer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClientAnswer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClientAnswer::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClientAnswer::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClientAnswer::InternalSwap(ClientAnswer* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.answer_, &other->_impl_.answer_, arena);
}

::google::protobuf::Metadata ClientAnswer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[1]);
}
// ===================================================================

class ServerQuestion::_Internal {
 public:
};

ServerQuestion::ServerQuestion(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ServerQuestion)
}
inline PROTOBUF_NDEBUG_INLINE ServerQuestion::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : question_(arena, from.question_),
        _cached_size_{0} {}

ServerQuestion::ServerQuestion(
    ::google::protobuf::Arena* arena,
    const ServerQuestion& from)
    : ::google::protobuf::Message(arena) {
  ServerQuestion* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ServerQuestion)
}
inline PROTOBUF_NDEBUG_INLINE ServerQuestion::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : question_(arena),
        _cached_size_{0} {}

inline void ServerQuestion::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ServerQuestion::~ServerQuestion() {
  // @@protoc_insertion_point(destructor:ServerQuestion)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServerQuestion::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.question_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServerQuestion::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerQuestion)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.question_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServerQuestion::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2> ServerQuestion::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ServerQuestion_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string question = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ServerQuestion, _impl_.question_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string question = 1;
    {PROTOBUF_FIELD_OFFSET(ServerQuestion, _impl_.question_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\10\0\0\0\0\0\0"
    "ServerQuestion"
    "question"
  }},
};

::uint8_t* ServerQuestion::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ServerQuestion)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string question = 1;
  if (!this->_internal_question().empty()) {
    const std::string& _s = this->_internal_question();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ServerQuestion.question");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServerQuestion)
  return target;
}

::size_t ServerQuestion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerQuestion)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string question = 1;
  if (!this->_internal_question().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_question());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServerQuestion::_class_data_ = {
    ServerQuestion::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServerQuestion::GetClassData() const {
  return &_class_data_;
}

void ServerQuestion::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServerQuestion*>(&to_msg);
  auto& from = static_cast<const ServerQuestion&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ServerQuestion)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_question().empty()) {
    _this->_internal_set_question(from._internal_question());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerQuestion::CopyFrom(const ServerQuestion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerQuestion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServerQuestion::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServerQuestion::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServerQuestion::InternalSwap(ServerQuestion* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.question_, &other->_impl_.question_, arena);
}

::google::protobuf::Metadata ServerQuestion::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[2]);
}
// ===================================================================

class ServerVerdict::_Internal {
 public:
};

ServerVerdict::ServerVerdict(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ServerVerdict)
}
inline PROTOBUF_NDEBUG_INLINE ServerVerdict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : answer_(arena, from.answer_),
        _cached_size_{0} {}

ServerVerdict::ServerVerdict(
    ::google::protobuf::Arena* arena,
    const ServerVerdict& from)
    : ::google::protobuf::Message(arena) {
  ServerVerdict* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.correct_ = from._impl_.correct_;

  // @@protoc_insertion_point(copy_constructor:ServerVerdict)
}
inline PROTOBUF_NDEBUG_INLINE ServerVerdict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : answer_(arena),
        _cached_size_{0} {}

inline void ServerVerdict::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.correct_ = {};
}
ServerVerdict::~ServerVerdict() {
  // @@protoc_insertion_point(destructor:ServerVerdict)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServerVerdict::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.answer_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServerVerdict::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerVerdict)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.answer_.ClearToEmpty();
  _impl_.correct_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServerVerdict::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> ServerVerdict::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ServerVerdict_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool correct = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServerVerdict, _impl_.correct_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ServerVerdict, _impl_.correct_)}},
    // string answer = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ServerVerdict, _impl_.answer_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string answer = 1;
    {PROTOBUF_FIELD_OFFSET(ServerVerdict, _impl_.answer_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool correct = 2;
    {PROTOBUF_FIELD_OFFSET(ServerVerdict, _impl_.correct_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\15\6\0\0\0\0\0\0"
    "ServerVerdict"
    "answer"
  }},
};

::uint8_t* ServerVerdict::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ServerVerdict)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string answer = 1;
  if (!this->_internal_answer().empty()) {
    const std::string& _s = this->_internal_answer();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ServerVerdict.answer");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool correct = 2;
  if (this->_internal_correct() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_correct(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServerVerdict)
  return target;
}

::size_t ServerVerdict::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerVerdict)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string answer = 1;
  if (!this->_internal_answer().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_answer());
  }

  // bool correct = 2;
  if (this->_internal_correct() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServerVerdict::_class_data_ = {
    ServerVerdict::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServerVerdict::GetClassData() const {
  return &_class_data_;
}

void ServerVerdict::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServerVerdict*>(&to_msg);
  auto& from = static_cast<const ServerVerdict&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ServerVerdict)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_answer().empty()) {
    _this->_internal_set_answer(from._internal_answer());
  }
  if (from._internal_correct() != 0) {
    _this->_internal_set_correct(from._internal_correct());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerVerdict::CopyFrom(const ServerVerdict& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerVerdict)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServerVerdict::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServerVerdict::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServerVerdict::InternalSwap(ServerVerdict* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.answer_, &other->_impl_.answer_, arena);
        swap(_impl_.correct_, other->_impl_.correct_);
}

::google::protobuf::Metadata ServerVerdict::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[3]);
}
// ===================================================================

class QuizFilePathsRequest::_Internal {
 public:
};

QuizFilePathsRequest::QuizFilePathsRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:QuizFilePathsRequest)
}
QuizFilePathsRequest::QuizFilePathsRequest(
    ::google::protobuf::Arena* arena,
    const QuizFilePathsRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  QuizFilePathsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:QuizFilePathsRequest)
}









::google::protobuf::Metadata QuizFilePathsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[4]);
}
// ===================================================================

class QuizFilePaths::_Internal {
 public:
};

QuizFilePaths::QuizFilePaths(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:QuizFilePaths)
}
inline PROTOBUF_NDEBUG_INLINE QuizFilePaths::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : quizpaths_{visibility, arena, from.quizpaths_},
        _cached_size_{0} {}

QuizFilePaths::QuizFilePaths(
    ::google::protobuf::Arena* arena,
    const QuizFilePaths& from)
    : ::google::protobuf::Message(arena) {
  QuizFilePaths* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:QuizFilePaths)
}
inline PROTOBUF_NDEBUG_INLINE QuizFilePaths::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : quizpaths_{visibility, arena},
        _cached_size_{0} {}

inline void QuizFilePaths::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
QuizFilePaths::~QuizFilePaths() {
  // @@protoc_insertion_point(destructor:QuizFilePaths)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void QuizFilePaths::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void QuizFilePaths::Clear() {
// @@protoc_insertion_point(message_clear_start:QuizFilePaths)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.quizpaths_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* QuizFilePaths::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2> QuizFilePaths::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_QuizFilePaths_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated string quizPaths = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(QuizFilePaths, _impl_.quizpaths_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string quizPaths = 1;
    {PROTOBUF_FIELD_OFFSET(QuizFilePaths, _impl_.quizpaths_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\15\11\0\0\0\0\0\0"
    "QuizFilePaths"
    "quizPaths"
  }},
};

::uint8_t* QuizFilePaths::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QuizFilePaths)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string quizPaths = 1;
  for (int i = 0, n = this->_internal_quizpaths_size(); i < n; ++i) {
    const auto& s = this->_internal_quizpaths().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "QuizFilePaths.quizPaths");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QuizFilePaths)
  return target;
}

::size_t QuizFilePaths::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QuizFilePaths)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string quizPaths = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_quizpaths().size());
  for (int i = 0, n = _internal_quizpaths().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_quizpaths().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData QuizFilePaths::_class_data_ = {
    QuizFilePaths::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* QuizFilePaths::GetClassData() const {
  return &_class_data_;
}

void QuizFilePaths::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<QuizFilePaths*>(&to_msg);
  auto& from = static_cast<const QuizFilePaths&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QuizFilePaths)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_quizpaths()->MergeFrom(from._internal_quizpaths());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QuizFilePaths::CopyFrom(const QuizFilePaths& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QuizFilePaths)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool QuizFilePaths::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* QuizFilePaths::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void QuizFilePaths::InternalSwap(QuizFilePaths* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.quizpaths_.InternalSwap(&other->_impl_.quizpaths_);
}

::google::protobuf::Metadata QuizFilePaths::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[5]);
}
// ===================================================================

class QuizChangeRequest::_Internal {
 public:
};

QuizChangeRequest::QuizChangeRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:QuizChangeRequest)
}
inline PROTOBUF_NDEBUG_INLINE QuizChangeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : quizpath_(arena, from.quizpath_),
        _cached_size_{0} {}

QuizChangeRequest::QuizChangeRequest(
    ::google::protobuf::Arena* arena,
    const QuizChangeRequest& from)
    : ::google::protobuf::Message(arena) {
  QuizChangeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.repeats_ = from._impl_.repeats_;

  // @@protoc_insertion_point(copy_constructor:QuizChangeRequest)
}
inline PROTOBUF_NDEBUG_INLINE QuizChangeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : quizpath_(arena),
        _cached_size_{0} {}

inline void QuizChangeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.repeats_ = {};
}
QuizChangeRequest::~QuizChangeRequest() {
  // @@protoc_insertion_point(destructor:QuizChangeRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void QuizChangeRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.quizpath_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void QuizChangeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:QuizChangeRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.quizpath_.ClearToEmpty();
  _impl_.repeats_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* QuizChangeRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> QuizChangeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_QuizChangeRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 repeats = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(QuizChangeRequest, _impl_.repeats_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(QuizChangeRequest, _impl_.repeats_)}},
    // string quizPath = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(QuizChangeRequest, _impl_.quizpath_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string quizPath = 1;
    {PROTOBUF_FIELD_OFFSET(QuizChangeRequest, _impl_.quizpath_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 repeats = 2;
    {PROTOBUF_FIELD_OFFSET(QuizChangeRequest, _impl_.repeats_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\10\0\0\0\0\0\0"
    "QuizChangeRequest"
    "quizPath"
  }},
};

::uint8_t* QuizChangeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QuizChangeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string quizPath = 1;
  if (!this->_internal_quizpath().empty()) {
    const std::string& _s = this->_internal_quizpath();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "QuizChangeRequest.quizPath");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 repeats = 2;
  if (this->_internal_repeats() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_repeats(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QuizChangeRequest)
  return target;
}

::size_t QuizChangeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QuizChangeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string quizPath = 1;
  if (!this->_internal_quizpath().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_quizpath());
  }

  // int32 repeats = 2;
  if (this->_internal_repeats() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_repeats());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData QuizChangeRequest::_class_data_ = {
    QuizChangeRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* QuizChangeRequest::GetClassData() const {
  return &_class_data_;
}

void QuizChangeRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<QuizChangeRequest*>(&to_msg);
  auto& from = static_cast<const QuizChangeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QuizChangeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_quizpath().empty()) {
    _this->_internal_set_quizpath(from._internal_quizpath());
  }
  if (from._internal_repeats() != 0) {
    _this->_internal_set_repeats(from._internal_repeats());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QuizChangeRequest::CopyFrom(const QuizChangeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QuizChangeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool QuizChangeRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* QuizChangeRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void QuizChangeRequest::InternalSwap(QuizChangeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quizpath_, &other->_impl_.quizpath_, arena);
        swap(_impl_.repeats_, other->_impl_.repeats_);
}

::google::protobuf::Metadata QuizChangeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[6]);
}
// ===================================================================

class PlayerDataMsg::_Internal {
 public:
};

PlayerDataMsg::PlayerDataMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PlayerDataMsg)
}
inline PROTOBUF_NDEBUG_INLINE PlayerDataMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

PlayerDataMsg::PlayerDataMsg(
    ::google::protobuf::Arena* arena,
    const PlayerDataMsg& from)
    : ::google::protobuf::Message(arena) {
  PlayerDataMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.score_ = from._impl_.score_;

  // @@protoc_insertion_point(copy_constructor:PlayerDataMsg)
}
inline PROTOBUF_NDEBUG_INLINE PlayerDataMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void PlayerDataMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.score_ = {};
}
PlayerDataMsg::~PlayerDataMsg() {
  // @@protoc_insertion_point(destructor:PlayerDataMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PlayerDataMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PlayerDataMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:PlayerDataMsg)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.score_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PlayerDataMsg::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 26, 2> PlayerDataMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PlayerDataMsg_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 score = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlayerDataMsg, _impl_.score_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PlayerDataMsg, _impl_.score_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PlayerDataMsg, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(PlayerDataMsg, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 score = 2;
    {PROTOBUF_FIELD_OFFSET(PlayerDataMsg, _impl_.score_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\15\4\0\0\0\0\0\0"
    "PlayerDataMsg"
    "name"
  }},
};

::uint8_t* PlayerDataMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PlayerDataMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PlayerDataMsg.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 score = 2;
  if (this->_internal_score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_score(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlayerDataMsg)
  return target;
}

::size_t PlayerDataMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlayerDataMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // int32 score = 2;
  if (this->_internal_score() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_score());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PlayerDataMsg::_class_data_ = {
    PlayerDataMsg::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PlayerDataMsg::GetClassData() const {
  return &_class_data_;
}

void PlayerDataMsg::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PlayerDataMsg*>(&to_msg);
  auto& from = static_cast<const PlayerDataMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PlayerDataMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_score() != 0) {
    _this->_internal_set_score(from._internal_score());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerDataMsg::CopyFrom(const PlayerDataMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlayerDataMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PlayerDataMsg::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PlayerDataMsg::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PlayerDataMsg::InternalSwap(PlayerDataMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        swap(_impl_.score_, other->_impl_.score_);
}

::google::protobuf::Metadata PlayerDataMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[7]);
}
// ===================================================================

class MessageEnvelope::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::MessageEnvelope, _impl_._oneof_case_);
  static const ::ClientLogin& clientlogin(const MessageEnvelope* msg);
  static const ::ClientAnswer& clientanswer(const MessageEnvelope* msg);
  static const ::ServerQuestion& serverquestion(const MessageEnvelope* msg);
  static const ::ServerVerdict& serververdict(const MessageEnvelope* msg);
  static const ::QuizChangeRequest& quizchangerequest(const MessageEnvelope* msg);
  static const ::QuizFilePathsRequest& quizfilepathsrequest(const MessageEnvelope* msg);
  static const ::QuizFilePaths& quizfilepaths(const MessageEnvelope* msg);
  static const ::PlayerDataMsg& playerdata(const MessageEnvelope* msg);
};

const ::ClientLogin& MessageEnvelope::_Internal::clientlogin(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.clientlogin_;
}
const ::ClientAnswer& MessageEnvelope::_Internal::clientanswer(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.clientanswer_;
}
const ::ServerQuestion& MessageEnvelope::_Internal::serverquestion(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.serverquestion_;
}
const ::ServerVerdict& MessageEnvelope::_Internal::serververdict(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.serververdict_;
}
const ::QuizChangeRequest& MessageEnvelope::_Internal::quizchangerequest(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.quizchangerequest_;
}
const ::QuizFilePathsRequest& MessageEnvelope::_Internal::quizfilepathsrequest(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.quizfilepathsrequest_;
}
const ::QuizFilePaths& MessageEnvelope::_Internal::quizfilepaths(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.quizfilepaths_;
}
const ::PlayerDataMsg& MessageEnvelope::_Internal::playerdata(const MessageEnvelope* msg) {
  return *msg->_impl_.payload_.playerdata_;
}
void MessageEnvelope::set_allocated_clientlogin(::ClientLogin* clientlogin) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (clientlogin) {
    ::google::protobuf::Arena* submessage_arena = clientlogin->GetArena();
    if (message_arena != submessage_arena) {
      clientlogin = ::google::protobuf::internal::GetOwnedMessage(message_arena, clientlogin, submessage_arena);
    }
    set_has_clientlogin();
    _impl_.payload_.clientlogin_ = clientlogin;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.clientLogin)
}
void MessageEnvelope::set_allocated_clientanswer(::ClientAnswer* clientanswer) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (clientanswer) {
    ::google::protobuf::Arena* submessage_arena = clientanswer->GetArena();
    if (message_arena != submessage_arena) {
      clientanswer = ::google::protobuf::internal::GetOwnedMessage(message_arena, clientanswer, submessage_arena);
    }
    set_has_clientanswer();
    _impl_.payload_.clientanswer_ = clientanswer;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.clientAnswer)
}
void MessageEnvelope::set_allocated_serverquestion(::ServerQuestion* serverquestion) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (serverquestion) {
    ::google::protobuf::Arena* submessage_arena = serverquestion->GetArena();
    if (message_arena != submessage_arena) {
      serverquestion = ::google::protobuf::internal::GetOwnedMessage(message_arena, serverquestion, submessage_arena);
    }
    set_has_serverquestion();
    _impl_.payload_.serverquestion_ = serverquestion;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.serverQuestion)
}
void MessageEnvelope::set_allocated_serververdict(::ServerVerdict* serververdict) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (serververdict) {
    ::google::protobuf::Arena* submessage_arena = serververdict->GetArena();
    if (message_arena != submessage_arena) {
      serververdict = ::google::protobuf::internal::GetOwnedMessage(message_arena, serververdict, submessage_arena);
    }
    set_has_serververdict();
    _impl_.payload_.serververdict_ = serververdict;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.serverVerdict)
}
void MessageEnvelope::set_allocated_quizchangerequest(::QuizChangeRequest* quizchangerequest) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (quizchangerequest) {
    ::google::protobuf::Arena* submessage_arena = quizchangerequest->GetArena();
    if (message_arena != submessage_arena) {
      quizchangerequest = ::google::protobuf::internal::GetOwnedMessage(message_arena, quizchangerequest, submessage_arena);
    }
    set_has_quizchangerequest();
    _impl_.payload_.quizchangerequest_ = quizchangerequest;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.quizChangeRequest)
}
void MessageEnvelope::set_allocated_quizfilepathsrequest(::QuizFilePathsRequest* quizfilepathsrequest) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (quizfilepathsrequest) {
    ::google::protobuf::Arena* submessage_arena = quizfilepathsrequest->GetArena();
    if (message_arena != submessage_arena) {
      quizfilepathsrequest = ::google::protobuf::internal::GetOwnedMessage(message_arena, quizfilepathsrequest, submessage_arena);
    }
    set_has_quizfilepathsrequest();
    _impl_.payload_.quizfilepathsrequest_ = quizfilepathsrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.quizFilePathsRequest)
}
void MessageEnvelope::set_allocated_quizfilepaths(::QuizFilePaths* quizfilepaths) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (quizfilepaths) {
    ::google::protobuf::Arena* submessage_arena = quizfilepaths->GetArena();
    if (message_arena != submessage_arena) {
      quizfilepaths = ::google::protobuf::internal::GetOwnedMessage(message_arena, quizfilepaths, submessage_arena);
    }
    set_has_quizfilepaths();
    _impl_.payload_.quizfilepaths_ = quizfilepaths;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.quizFilePaths)
}
void MessageEnvelope::set_allocated_playerdata(::PlayerDataMsg* playerdata) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (playerdata) {
    ::google::protobuf::Arena* submessage_arena = playerdata->GetArena();
    if (message_arena != submessage_arena) {
      playerdata = ::google::protobuf::internal::GetOwnedMessage(message_arena, playerdata, submessage_arena);
    }
    set_has_playerdata();
    _impl_.payload_.playerdata_ = playerdata;
  }
  // @@protoc_insertion_point(field_set_allocated:MessageEnvelope.playerData)
}
MessageEnvelope::MessageEnvelope(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MessageEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE MessageEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

MessageEnvelope::MessageEnvelope(
    ::google::protobuf::Arena* arena,
    const MessageEnvelope& from)
    : ::google::protobuf::Message(arena) {
  MessageEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.type_ = from._impl_.type_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kClientLogin:
        _impl_.payload_.clientlogin_ = CreateMaybeMessage<::ClientLogin>(arena, *from._impl_.payload_.clientlogin_);
        break;
      case kClientAnswer:
        _impl_.payload_.clientanswer_ = CreateMaybeMessage<::ClientAnswer>(arena, *from._impl_.payload_.clientanswer_);
        break;
      case kServerQuestion:
        _impl_.payload_.serverquestion_ = CreateMaybeMessage<::ServerQuestion>(arena, *from._impl_.payload_.serverquestion_);
        break;
      case kServerVerdict:
        _impl_.payload_.serververdict_ = CreateMaybeMessage<::ServerVerdict>(arena, *from._impl_.payload_.serververdict_);
        break;
      case kQuizChangeRequest:
        _impl_.payload_.quizchangerequest_ = CreateMaybeMessage<::QuizChangeRequest>(arena, *from._impl_.payload_.quizchangerequest_);
        break;
      case kQuizFilePathsRequest:
        _impl_.payload_.quizfilepathsrequest_ = CreateMaybeMessage<::QuizFilePathsRequest>(arena, *from._impl_.payload_.quizfilepathsrequest_);
        break;
      case kQuizFilePaths:
        _impl_.payload_.quizfilepaths_ = CreateMaybeMessage<::QuizFilePaths>(arena, *from._impl_.payload_.quizfilepaths_);
        break;
      case kPlayerData:
        _impl_.payload_.playerdata_ = CreateMaybeMessage<::PlayerDataMsg>(arena, *from._impl_.payload_.playerdata_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:MessageEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE MessageEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void MessageEnvelope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
MessageEnvelope::~MessageEnvelope() {
  // @@protoc_insertion_point(destructor:MessageEnvelope)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MessageEnvelope::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
  _impl_.~Impl_();
}

void MessageEnvelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:MessageEnvelope)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (payload_case()) {
    case kClientLogin: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.clientlogin_;
      }
      break;
    }
    case kClientAnswer: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.clientanswer_;
      }
      break;
    }
    case kServerQuestion: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.serverquestion_;
      }
      break;
    }
    case kServerVerdict: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.serververdict_;
      }
      break;
    }
    case kQuizChangeRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.quizchangerequest_;
      }
      break;
    }
    case kQuizFilePathsRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.quizfilepathsrequest_;
      }
      break;
    }
    case kQuizFilePaths: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.quizfilepaths_;
      }
      break;
    }
    case kPlayerData: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.playerdata_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


PROTOBUF_NOINLINE void MessageEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageEnvelope)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MessageEnvelope::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 9, 8, 0, 2> MessageEnvelope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    8,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MessageEnvelope_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .MessageEnvelope.MessageType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageEnvelope, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MessageEnvelope.MessageType type = 1;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .ClientLogin clientLogin = 2;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.clientlogin_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ClientAnswer clientAnswer = 3;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.clientanswer_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ServerQuestion serverQuestion = 4;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.serverquestion_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ServerVerdict serverVerdict = 5;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.serververdict_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .QuizChangeRequest quizChangeRequest = 6;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.quizchangerequest_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .QuizFilePathsRequest quizFilePathsRequest = 7;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.quizfilepathsrequest_), _Internal::kOneofCaseOffset + 0, 5,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvDefault)},
    // .QuizFilePaths quizFilePaths = 8;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.quizfilepaths_), _Internal::kOneofCaseOffset + 0, 6,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .PlayerDataMsg playerData = 9;
    {PROTOBUF_FIELD_OFFSET(MessageEnvelope, _impl_.payload_.playerdata_), _Internal::kOneofCaseOffset + 0, 7,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ClientLogin>()},
    {::_pbi::TcParser::GetTable<::ClientAnswer>()},
    {::_pbi::TcParser::GetTable<::ServerQuestion>()},
    {::_pbi::TcParser::GetTable<::ServerVerdict>()},
    {::_pbi::TcParser::GetTable<::QuizChangeRequest>()},
    {::_pbi::FieldAuxDefaultMessage{}, &::_QuizFilePathsRequest_default_instance_},
    {::_pbi::TcParser::GetTable<::QuizFilePaths>()},
    {::_pbi::TcParser::GetTable<::PlayerDataMsg>()},
  }}, {{
  }},
};

::uint8_t* MessageEnvelope::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .MessageEnvelope.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  switch (payload_case()) {
    case kClientLogin: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::clientlogin(this),
          _Internal::clientlogin(this).GetCachedSize(), target, stream);
      break;
    }
    case kClientAnswer: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::clientanswer(this),
          _Internal::clientanswer(this).GetCachedSize(), target, stream);
      break;
    }
    case kServerQuestion: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, _Internal::serverquestion(this),
          _Internal::serverquestion(this).GetCachedSize(), target, stream);
      break;
    }
    case kServerVerdict: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, _Internal::serververdict(this),
          _Internal::serververdict(this).GetCachedSize(), target, stream);
      break;
    }
    case kQuizChangeRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, _Internal::quizchangerequest(this),
          _Internal::quizchangerequest(this).GetCachedSize(), target, stream);
      break;
    }
    case kQuizFilePathsRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, _Internal::quizfilepathsrequest(this),
          _Internal::quizfilepathsrequest(this).GetCachedSize(), target, stream);
      break;
    }
    case kQuizFilePaths: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, _Internal::quizfilepaths(this),
          _Internal::quizfilepaths(this).GetCachedSize(), target, stream);
      break;
    }
    case kPlayerData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          9, _Internal::playerdata(this),
          _Internal::playerdata(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageEnvelope)
  return target;
}

::size_t MessageEnvelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MessageEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .MessageEnvelope.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  switch (payload_case()) {
    // .ClientLogin clientLogin = 2;
    case kClientLogin: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.clientlogin_);
      break;
    }
    // .ClientAnswer clientAnswer = 3;
    case kClientAnswer: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.clientanswer_);
      break;
    }
    // .ServerQuestion serverQuestion = 4;
    case kServerQuestion: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.serverquestion_);
      break;
    }
    // .ServerVerdict serverVerdict = 5;
    case kServerVerdict: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.serververdict_);
      break;
    }
    // .QuizChangeRequest quizChangeRequest = 6;
    case kQuizChangeRequest: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.quizchangerequest_);
      break;
    }
    // .QuizFilePathsRequest quizFilePathsRequest = 7;
    case kQuizFilePathsRequest: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.quizfilepathsrequest_);
      break;
    }
    // .QuizFilePaths quizFilePaths = 8;
    case kQuizFilePaths: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.quizfilepaths_);
      break;
    }
    // .PlayerDataMsg playerData = 9;
    case kPlayerData: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_.playerdata_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MessageEnvelope::_class_data_ = {
    MessageEnvelope::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MessageEnvelope::GetClassData() const {
  return &_class_data_;
}

void MessageEnvelope::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MessageEnvelope*>(&to_msg);
  auto& from = static_cast<const MessageEnvelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MessageEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  switch (from.payload_case()) {
    case kClientLogin: {
      _this->_internal_mutable_clientlogin()->::ClientLogin::MergeFrom(
          from._internal_clientlogin());
      break;
    }
    case kClientAnswer: {
      _this->_internal_mutable_clientanswer()->::ClientAnswer::MergeFrom(
          from._internal_clientanswer());
      break;
    }
    case kServerQuestion: {
      _this->_internal_mutable_serverquestion()->::ServerQuestion::MergeFrom(
          from._internal_serverquestion());
      break;
    }
    case kServerVerdict: {
      _this->_internal_mutable_serververdict()->::ServerVerdict::MergeFrom(
          from._internal_serververdict());
      break;
    }
    case kQuizChangeRequest: {
      _this->_internal_mutable_quizchangerequest()->::QuizChangeRequest::MergeFrom(
          from._internal_quizchangerequest());
      break;
    }
    case kQuizFilePathsRequest: {
      _this->_internal_mutable_quizfilepathsrequest()->::QuizFilePathsRequest::MergeFrom(
          from._internal_quizfilepathsrequest());
      break;
    }
    case kQuizFilePaths: {
      _this->_internal_mutable_quizfilepaths()->::QuizFilePaths::MergeFrom(
          from._internal_quizfilepaths());
      break;
    }
    case kPlayerData: {
      _this->_internal_mutable_playerdata()->::PlayerDataMsg::MergeFrom(
          from._internal_playerdata());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageEnvelope::CopyFrom(const MessageEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MessageEnvelope::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MessageEnvelope::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MessageEnvelope::InternalSwap(MessageEnvelope* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MessageEnvelope::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fPackets_2eproto_getter, &descriptor_table_src_2fPackets_2eproto_once,
      file_level_metadata_src_2fPackets_2eproto[8]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
